CREATE WAREHOUSE SALES_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

SHOW WAREHOUSES;

CREATE DATABASE CUSTOMER_SALES_DB;

SHOW DATABASES;

CREATE SCHEMA CUSTOMER_SALES_DB.SALES_SCHEMA;

USE SCHEMA CUSTOMER_SALES_DB.SALES_SCHEMA;

CREATE FILE FORMAT CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE STAGE CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_STAGE
FILE_FORMAT = CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_CSV_FORMAT;


LIST @CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_STAGE;


create table CUSTOMER_SALES_DB.SALES_SCHEMA.CUSTOMERS(
customer_id NUMBER,
first_name VARCHAR(50),
last_name VARCHAR(50),
email VARCHAR(100),
phone VARCHAR(20),
address VARCHAR(100)
);

create table CUSTOMER_SALES_DB.SALES_SCHEMA.FoodItems(
food_id NUMBER,
name VARCHAR(50),
price NUMBER(10, 2),
category VARCHAR(50),
avaliability VARCHAR(20)
);

create table CUSTOMER_SALES_DB.SALES_SCHEMA.ORDERS(
order_id NUMBER,
customer_id NUMBER,
food_id NUMBER,
quantity NUMBER,
order_date TIMESTAMP_NTZ,
status VARCHAR(30),
total_amount NUMBER(10, 2)
);



COPY INTO CUSTOMER_SALES_DB.SALES_SCHEMA.CUSTOMERS
FROM @CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_STAGE/customers.csv
FILE_FORMAT = (
FORMAT_NAME = 'CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';



COPY INTO CUSTOMER_SALES_DB.SALES_SCHEMA.FoodItems
FROM @CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_STAGE/fooditems.csv
FILE_FORMAT = (
FORMAT_NAME = 'CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT'



COPY INTO CUSTOMER_SALES_DB.SALES_SCHEMA.ORDERS
FROM @CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_STAGE/orders.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT * 
FROM CUSTOMER_SALES_DB.SALES_SCHEMA.CUSTOMERS;

SELECT * 
FROM CUSTOMER_SALES_DB.SALES_SCHEMA.FoodItems;

SELECT * 
FROM CUSTOMER_SALES_DB.SALES_SCHEMA.ORDERS;



SELECT c.customer_id,
concat(c.first_name,' ',c.last_name) as Customer_name,
sum(o.TOTAL_AMOUNT) as Total_Spent
from CUSTOMERS c 
INNER JOIN ORDERS o
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.first_name, c.last_name
order by c.customer_id


SELECT C.CUSTOMER_ID,
CONCAT(C.FIRST_NAME,' ', C.LAST_NAME),
SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C 
INNER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 1;

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS

SELECT FI.CATEGORY,
SUM(O.TOTAL_AMOUNT) AS REVENUE
FROM FOODITEMS FI 
INNER JOIN ORDERS O 
ON FI.FOOD_ID = O.FOOD_ID
GROUP BY FI.CATEGORY
ORDER BY REVENUE DESC

SELECT STATUS AS ORDER_STATUS,
SUM(TOTAL_AMOUNT) AS REVENUE
FROM ORDERS
GROUP BY STATUS

SELECT
concat(c.first_name,' ',c.last_name) as Customer_name,
sum(o.TOTAL_AMOUNT) as Total_Spent
from CUSTOMERS c 
INNER JOIN ORDERS o
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY c.first_name, c.last_name
order by Total_Spent DESC
LIMIT 3

SELECT C.CUSTOMER_ID,
CONCAT(C.FIRST_NAME,' ',C.LAST_NAME),
COUNT(O.CUSTOMER_ID) AS ORDERS_PLACED
FROM CUSTOMERS C 
INNER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.FIRST_NAME, C.LAST_NAME
ORDER BY ORDERS_PLACED DESC

SELECT ORDER_ID,
CUSTOMER_ID,
FOOD_ID,
STATUS,
TOTAL_AMOUNT
FROM ORDERS
WHERE STATUS = 'Delivered';


SELECT O.ORDER_ID,
CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) AS CUSTOMER_NAME,
O.ORDER_DATE,
O.STATUS,
O.TOTAL_AMOUNT
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE ORDER_DATE > '2026-07-12 23:59:59'


CREATE OR REPLACE VIEW CUSTOMER_SALES_REPORT AS 
SELECT C.CUSTOMER_ID,
CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) AS CUSTOMER_NAME,
SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT_SPENT
FROM CUSTOMERS C 
INNER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.ORDER_ID
GROUP BY C.CUSTOMER_ID, C.FIRST_NAME,C.LAST_NAME
