CREATE WAREHOUSE RETAIL_WH
WITH
    WAREHOUSE_SIZE ='XSMALL',
    AUTO_SUSPEND = 60
    AUTO_RESUME =  TRUE;

CREATE DATABASE RETAIL_DB;
CREATE SCHEMA RETAIL_DB.SALES_SCHEMA;

CREATE FILE FORMAT RETAIL_DB.SALES_SCHEMA.SALES_CSV_FORMAT
TYPE = 'CSV',
FIELD_DELIMITER = ',',
SKIP_HEADER = 1;

CREATE STAGE RETAIL_DB.SALES_SCHEMA.SALES_STAGE
FILE_FORMAT = RETAIL_DB.SALES_SCHEMA.SALES_CSV_FORMAT;

CREATE TABLE RETAIL_DB.SALES_SCHEMA.CUSTOMERS(
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(30),
CITY VARCHAR(50),
MEMBERSHIP VARCHAR(30)
);

CREATE TABLE RETAIL_DB.SALES_SCHEMA.PRODUCTS(
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR(30),
CATEGORY VARCHAR(30),
PRICE NUMBER(10, 2)
);

CREATE TABLE RETAIL_DB.SALES_SCHEMA.BRANCHES(
BRANCH_ID NUMBER,
BRANCH_NAME VARCHAR(30),
CITY VARCHAR(30)
);

CREATE TABLE RETAIL_DB.SALES_SCHEMA.SALES(
SALE_ID NUMBER,
CUSTOMER_ID NUMBER,
PRODUCT_ID NUMBER,
BRANCH_ID NUMBER,
QUANTITY NUMBER,
SALE_DATE TIMESTAMP_NTZ,
TOTAL_AMOUNT NUMBER(10, 2)
);

COPY INTO RETAIL_DB.SALES_SCHEMA.CUSTOMERS
FROM @RETAIL_DB.SALES_SCHEMA.SALES_STAGE/customers.csv
FILE_FORMAT = (
FORMAT_NAME = 'RETAIL_DB.SALES_SCHEMA.SALES_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT'

COPY INTO RETAIL_DB.SALES_SCHEMA.PRODUCTS
FROM @RETAIL_DB.SALES_SCHEMA.SALES_STAGE/products.csv
FILE_FORMAT = (
FORMAT_NAME = 'RETAIL_DB.SALES_SCHEMA.SALES_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT'

COPY INTO RETAIL_DB.SALES_SCHEMA.SALES
FROM @RETAIL_DB.SALES_SCHEMA.SALES_STAGE/sales.csv
FILE_FORMAT = (
FORMAT_NAME = 'RETAIL_DB.SALES_SCHEMA.SALES_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT'

COPY INTO RETAIL_DB.SALES_SCHEMA.BRANCHES
FROM @RETAIL_DB.SALES_SCHEMA.SALES_STAGE/branches.csv
FILE_FORMAT = (
FORMAT_NAME = 'RETAIL_DB.SALES_SCHEMA.SALES_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT'

SELECT * 
FROM RETAIL_DB.SALES_SCHEMA.CUSTOMERS;

SELECT * 
FROM RETAIL_DB.SALES_SCHEMA.SALES;

SELECT * 
FROM RETAIL_DB.SALES_SCHEMA.PRODUCTS;

SELECT * 
FROM RETAIL_DB.SALES_SCHEMA.BRANCHES;

SELECT
SUM(TOTAL_AMOUNT) AS TOTAL_BUSINESS_REVENUE
FROM SALES;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.MEMBERSHIP,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.MEMBERSHIP
ORDER BY TOTAL_SPENDING DESC;


SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(S.QUANTITY) AS TOTAL_QUANTITY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;


SELECT
    P.CATEGORY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 1;


SELECT
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;


SELECT
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 3;


SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;


SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS BRANCH_RANK
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY BRANCH_RANK;



SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    TOTAL_REVENUE
FROM (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE,
        ROW_NUMBER() OVER (
            PARTITION BY P.CATEGORY
            ORDER BY SUM(S.TOTAL_AMOUNT) DESC
        ) AS RN
    FROM PRODUCTS P
    JOIN SALES S
        ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY
)
WHERE RN = 1;

SELECT
    SALE_DATE,
    SALE_ID,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALE_DATE
    ) AS CUMULATIVE_SALES
FROM SALES
ORDER BY SALE_DATE;

SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    AVG(TOTAL_AMOUNT) OVER () AS AVERAGE_SALE_AMOUNT
FROM SALES
ORDER BY SALE_ID;


WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        C.CITY,
        C.MEMBERSHIP,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM RETAIL_DB.SALES_SCHEMA.CUSTOMERS C
    JOIN RETAIL_DB.SALES_SCHEMA.SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        C.CITY,
        C.MEMBERSHIP
)
SELECT *
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM CUSTOMERS C
    JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
),

AVERAGE_REVENUE AS (
    SELECT
        AVG(TOTAL_REVENUE) AS AVG_REVENUE
    FROM CUSTOMER_REVENUE
)

SELECT
    CR.CUSTOMER_ID,
    CR.CUSTOMER_NAME,
    CR.TOTAL_REVENUE,
    AR.AVG_REVENUE
FROM CUSTOMER_REVENUE CR
CROSS JOIN AVERAGE_REVENUE AR
WHERE CR.TOTAL_REVENUE > AR.AVG_REVENUE
ORDER BY CR.TOTAL_REVENUE DESC;


CREATE OR REPLACE VIEW RETAIL_DB.SALES_SCHEMA.SALES_REPORT AS
SELECT
    S.SALE_ID,
    S.SALE_DATE,
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP,
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY AS BRANCH_CITY,
    S.QUANTITY,
    P.PRICE,
    S.TOTAL_AMOUNT
FROM SALES S
JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN BRANCHES B
    ON S.BRANCH_ID = B.BRANCH_ID;


SELECT *
FROM SALES_REPORT
ORDER BY SALE_ID;


CREATE OR REPLACE VIEW RETAIL_DB.SALES_SCHEMA.TOP_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM RETAIL_DB.SALES_SCHEMA.SALES
GROUP BY CUSTOMER_ID;



SELECT
    CUSTOMER_ID,
    TOTAL_SPENDING
FROM RETAIL_DB.SALES_SCHEMA.TOP_CUSTOMERS
ORDER BY TOTAL_SPENDING DESC;




SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP,
    TC.TOTAL_SPENDING
FROM RETAIL_DB.SALES_SCHEMA.TOP_CUSTOMERS TC
JOIN RETAIL_DB.SALES_SCHEMA.CUSTOMERS C
    ON TC.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY TC.TOTAL_SPENDING DESC;




SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    TC.TOTAL_SPENDING
FROM RETAIL_DB.SALES_SCHEMA.TOP_CUSTOMERS TC
JOIN RETAIL_DB.SALES_SCHEMA.CUSTOMERS C
    ON TC.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY TC.TOTAL_SPENDING DESC
LIMIT 3;